services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API port (Used by Python client)
      - "6334:6334" # gRPC port (Used for faster, high-performance connections)
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongodb:
  qdrant_data: # Added volume to persist your vectors